# Generated by Django 3.2.8 on 2021-11-07 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pressure', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodpressure',
            name='note',
        ),
    ]
