# Generated by Django 3.2.8 on 2021-10-30 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='metric',
            field=models.CharField(choices=[('CELSIUS', 'metric'), ('FAHRENHEIT', 'imperial')], default='CELSIUS', max_length=10),
        ),
    ]
