# Generated by Django 3.2.8 on 2021-10-15 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('temperature', models.CharField(max_length=10)),
                ('atmosphere_pressure', models.CharField(max_length=10)),
                ('humidity', models.CharField(max_length=10)),
                ('icon', models.CharField(max_length=10)),
            ],
        ),
    ]
